### ISSUE TITLE
Ensure dependency vulnerability database is updated on a regular cadence

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-java-dependencies#15]
Right now the recipe goes off a [static snapshot](https://github.com/openrewrite/rewrite-java-dependencies/blob/ead72908e86629d55e6dbbfbee80bf52cf410754/src/main/resources/advisories.csv) of the github security advisory database. We need an automatic process, or a regularly repeated manual process, which keeps this database up to date

**Comment by timtebeek** [comment]
Looking briefly we already have:
1. a [utility class](https://github.com/openrewrite/rewrite-java-dependencies/blob/fb1f022fb78ac7492eb5357643b799fde60aed7b/src/main/java/org/openrewrite/java/dependencies/github/ParseAdvisories.java#L58-L59) to parse https://github.com/github/advisory-database
2. write that out to [src/main/resources/advisories.csv](https://github.com/openrewrite/rewrite-java-dependencies/blob/main/src/main/resources/advisories.csv)
3. which is then [used in the recipe](https://github.com/openrewrite/rewrite-java-dependencies/blob/fb1f022fb78ac7492eb5357643b799fde60aed7b/src/main/java/org/openrewrite/java/dependencies/DependencyVulnerabilityCheck.java#L131-L134)

To periodically update `advisories.csv` we could for instance write a scheduled GitHub Actions workflow that
1. clones github/advisory-database
2. runs the utility to update advisories.csv
3. creates & assigns a pull request ([example](https://github.com/moderneinc/jenkins-ingest/blob/5833b9b250aa56a0d2d8c0d231ab2d1f2197bbd9/.github/workflows/addGitHubOrganization.yaml#L32-L34))

That would make the above part of the usual flow for changes, with review, merge & release as manual steps.

If we want to go a step further in our update automation we can skip or automatically merge PRs, and potentially even do patch releases automatically such that these new vulnerabilities become available.

In terms of alternatives we could also pull advisories.csv up into a separate repository, which we can then release on a for instance daily schedule with [calendar versioning](https://calver.org/).

Any other thoughts or considerations you'd want to log here before it's picked up @sambsnyd ?
And would you want to pick this up yourself, or would you want anyone else involved?

**Comment by rpau** [comment]
@timtebeek I have discussed this f2f and this will be picked up by the devex team.
